// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'Only Android and iOS platforms are supported for this application.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_k88K08UUl9UKetuWyjtnhdkiug6s7FY',
    appId: '1:466353420949:android:38ef56248efd05220f799c',
    messagingSenderId: '466353420949',
    projectId: 'meetmaxi-apr-2025-6ed9d',
    storageBucket: 'meetmaxi-apr-2025-6ed9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyUrMFq7wL7CXp8mRyLByuEvaFH6oxgDs',
    appId: '1:466353420949:ios:62e0a4bc0146016a0f799c',
    messagingSenderId: '466353420949',
    projectId: 'meetmaxi-apr-2025-6ed9d',
    storageBucket: 'meetmaxi-apr-2025-6ed9d.firebasestorage.app',
    iosClientId: '466353420949-e81a934g9nfoosl1enr7anf4joiah76d.apps.googleusercontent.com',
    iosBundleId: 'ai.axarsoft.askmaxie',
  );

}